"""Configuration persistence and safe atomic update management.

Implements safe configuration writes with pre-validation, temporary files,
and automatic rollback to prevent configuration corruption.
"""

from __future__ import annotations

import os
import shutil
import tempfile
from pathlib import Path
from typing import Optional

from device_guardian.config import AppConfig, ConfigurationError, load_config
from device_guardian.logger import get_logger

logger = get_logger("setup.storage")


def format_env_file(config: AppConfig) -> str:
    """Format an AppConfig instance into clean, documented .env file content."""
    raw_token = config.get_secret_token().strip() if hasattr(config, "get_secret_token") else str(config.telegram_bot_token).strip()
    raw_chat_id = config.get_secret_chat_id().strip() if hasattr(config, "get_secret_chat_id") else str(config.telegram_chat_id).strip()

    return (
        "# Device Guardian Local Configuration\n"
        "# Automatically generated by Device Guardian Setup Wizard\n"
        "# NEVER commit this file to version control.\n\n"
        f"TELEGRAM_BOT_TOKEN={raw_token}\n"
        f"TELEGRAM_CHAT_ID={raw_chat_id}\n"
        f"LOCATION_API_URL={config.location_api_url.strip()}\n"
        f"CAMERA_INDEX={config.camera_index}\n"
        f"REQUEST_TIMEOUT_SECONDS={config.request_timeout_seconds}\n"
        f"LOG_LEVEL={config.log_level.strip()}\n"
        f"AUTH_FAILURE_THRESHOLD={config.auth_failure_threshold}\n"
        f"AUTH_FAILURE_WINDOW_SECONDS={config.auth_failure_window_seconds}\n"
        f"AUTH_ALERT_COOLDOWN_SECONDS={config.auth_alert_cooldown_seconds}\n"
        f"VOICE_WARNING_ENABLED={'true' if config.voice_warning_enabled else 'false'}\n"
        f"VOICE_WARNING_TEXT={config.voice_warning_text.strip()}\n"
        f"VOICE_WARNING_COOLDOWN_SECONDS={config.voice_warning_cooldown_seconds}\n"
        f"SMART_FILTERING_ENABLED={'true' if getattr(config, 'smart_filtering_enabled', True) else 'false'}\n"
        f"DEVICE_GUARDIAN_TRUSTED_USERS={','.join(getattr(config, 'trusted_users', []))}\n"
        f"DEVICE_GUARDIAN_TRUSTED_NETWORKS={','.join(getattr(config, 'trusted_networks', []))}\n"
        f"DEVICE_GUARDIAN_TRUSTED_AUTH_TYPES={','.join(getattr(config, 'trusted_auth_types', []))}\n"
        f"ENVIRONMENTAL_TRIGGERS_ENABLED={'true' if getattr(config, 'environmental_triggers_enabled', True) else 'false'}\n"
        f"NETWORK_CONTEXT_ENABLED={'true' if getattr(config, 'network_context_enabled', True) else 'false'}\n"
        f"DEVICE_STATE_CONTEXT_ENABLED={'true' if getattr(config, 'device_state_context_enabled', True) else 'false'}\n"
        f"REQUIRE_CONTEXT_FOR_ALERT={'true' if getattr(config, 'require_context_for_alert', False) else 'false'}\n"
        f"CAMERA_ALERT_ENABLED={'true' if getattr(config, 'camera_alert_enabled', True) else 'false'}\n"
        f"LOCATION_ALERT_ENABLED={'true' if getattr(config, 'location_alert_enabled', True) else 'false'}\n"
        f"TELEGRAM_ALERT_ENABLED={'true' if getattr(config, 'telegram_alert_enabled', True) else 'false'}\n"
        f"BACKGROUND_MODE_ENABLED={'true' if getattr(config, 'background_mode_enabled', False) else 'false'}\n"
        f"TRAY_ENABLED={'true' if getattr(config, 'tray_enabled', True) else 'false'}\n"
        f"START_WITH_SYSTEM={'true' if getattr(config, 'start_with_system', False) else 'false'}\n"
        f"SINGLE_INSTANCE_ENABLED={'true' if getattr(config, 'single_instance_enabled', True) else 'false'}\n"
        f"AUTO_RESTART_ENABLED={'true' if getattr(config, 'auto_restart_enabled', True) else 'false'}\n"
        f"MAX_RESTART_ATTEMPTS={getattr(config, 'max_restart_attempts', 3)}\n"
        f"RESTART_BACKOFF_SECONDS={getattr(config, 'restart_backoff_seconds', 2.0)}\n"
        f"CAMERA_PHOTO_COUNT={getattr(config, 'camera_photo_count', 3)}\n"
        f"EXACT_LATITUDE={getattr(config, 'exact_latitude', '') if getattr(config, 'exact_latitude', None) is not None else ''}\n"
        f"EXACT_LONGITUDE={getattr(config, 'exact_longitude', '') if getattr(config, 'exact_longitude', None) is not None else ''}\n"
        f"EXACT_LOCATION_NAME={getattr(config, 'exact_location_name', '') or ''}\n"
    )


def safe_save_config(
    config: AppConfig,
    target_path: Optional[Path | str] = None,
) -> Path:
    """Safely persist configuration to disk using an atomic replacement strategy.

    Workflow:
        1. Pre-validate candidate AppConfig object in memory.
        2. Write contents to a temporary file (.env.tmp).
        3. Re-read and re-validate temporary file using load_config().
        4. Backup existing .env file (.env.bak) if one exists.
        5. Atomically replace .env with .env.tmp.
        6. Clean up temporary files.
        7. On any failure, automatically restore .env.bak to prevent corruption.

    Args:
        config: The AppConfig instance to save.
        target_path: Optional destination path (defaults to .env in cwd).

    Returns:
        Path to the saved configuration file.

    Raises:
        ConfigurationError: If the configuration is invalid or cannot be safely written.
    """
    # Step 1: Pre-validate in-memory configuration
    config.validate()

    resolved_path = (
        Path(target_path).resolve() if target_path else Path.cwd() / ".env"
    )
    resolved_path.parent.mkdir(parents=True, exist_ok=True)

    temp_path = resolved_path.parent / f"{resolved_path.name}.tmp"
    backup_path = resolved_path.parent / f"{resolved_path.name}.bak"
    had_existing_file = resolved_path.is_file()

    env_content = format_env_file(config)

    try:
        # Step 2: Write to temporary file
        temp_path.write_text(env_content, encoding="utf-8")

        # Step 3: Validate that the temporary file can be loaded and validated
        test_loaded = load_config(env_path=temp_path)
        test_loaded.validate()

        # Step 4: Backup existing configuration if present
        if had_existing_file:
            shutil.copy2(resolved_path, backup_path)
            logger.debug("Existing configuration backed up to: %s", backup_path)

        # Step 5: Replace target file with temporary file
        # os.replace provides atomic replacement on POSIX and modern Windows
        os.replace(temp_path, resolved_path)

        # Secure file permissions on POSIX systems (owner read/write only)
        if hasattr(os, "chmod") and os.name != "nt":
            try:
                os.chmod(resolved_path, 0o600)
            except Exception:
                pass

        logger.info("Configuration successfully written to: %s", resolved_path)

        # Clean up backup file if successful
        if backup_path.is_file():
            try:
                backup_path.unlink()
            except Exception:
                pass

        return resolved_path

    except Exception as exc:
        logger.error("Configuration save failed: %s. Initiating rollback...", exc)

        # Clean up temporary file
        if temp_path.is_file():
            try:
                temp_path.unlink()
            except Exception:
                pass

        # Step 7: Rollback if existing file was affected
        if had_existing_file and backup_path.is_file() and not resolved_path.is_file():
            try:
                os.replace(backup_path, resolved_path)
                logger.info("Restored previous working configuration from backup.")
            except Exception as rollback_err:
                logger.critical("Failed to rollback configuration: %s", rollback_err)

        raise ConfigurationError(
            f"Failed to safely save configuration: {exc}"
        ) from exc
